from prometheus_client import (Counter, Histogram, Gauge)
REQUEST_COUNT = Counter("gateway_requests_total","Total gateway requests",["provider", "status"])
REQUEST_LATENCY = Histogram("gateway_request_latency_seconds","Request latency",["provider"])
FALLBACK_COUNT = Counter("gateway_fallback_total","Total provider fallbacks")
PROVIDER_HEALTH = Gauge("provider_health_status", "Provider health status", ["provider"])

ACTIVE_STREAMS = Gauge("gateway_active_streams", "Total streaming requests")
STREAM_COUNT = Counter("gateway_stream_total","Total streaming requests")
STREAM_FAILURES = Counter("gateway_stream_failures_total","Total stream failures")
STREAM_DURATION = Histogram("gateway_stream_duration_seconds","Streaming request duration")
TOKENS_STREAMED = Counter("gateway_tokens_streamed_total","Total streamed tokens")
SIMULATED_FAILURES = Counter("gateway_simulated_failures_total", "Total simulated provider failures",
                             ["provider"])
RETRY_COUNT = Counter("gateway_retry_total", "Total provider retries", ["provider"])
PROVIDER_ACTIVE_LOAD = Gauge("provider_active_requests","Current provider active requests",["provider"])
GLOBAL_ACTIVE_REQUESTS = Gauge("gateway_global_active_requests","Current active gateway requests")
REJECTED_REQUESTS = Counter("gateway_rejected_requests_total","Rejected requests",["reason"])
QUEUE_SIZE = Gauge("gateway_queue_size","Queue size",["queue"])
SCHEDULED_REQUESTS = Counter("gateway_scheduled_requests_total","Scheduled requests",["queue"])
QUEUE_WAIT_TIME = Histogram("gateway_queue_wait_seconds","Queue wait time")
TENANT_REJECTIONS = Counter("gateway_tenant_rejections_total","Tenant isolation rejections",["tier"])
TOKEN_USAGE = Counter("gateway_tokens_used_total","Total token usage",["tier"])
ESTIMATED_COST = Counter("gateway_estimated_cost_total","Estimated provider cost",["provider"])

